import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import CampaignCard from '../components/card.jsx'
import { createClient } from 'contentful'

export async function getStaticProps() {

  const client = createClient({
    space: 'svltlb1ky1ti',
    accessToken: 'VKaKj9cGGuJ5lgCxTVych8ny-vGF3HGP_cow0828Yuk',
  })

  const res = await client.getEntries({ content_type: 'campaigns' })

  return {
    props: {
      campaigns: res.items
    }
  }

}

// export default function Campaigns({campaigns}) {
//   console.log(campaigns);
//   return (
//     <div className="Campaigns">
//       This is just to see the data***
//     </div>
//   )
// }

export default function Home({campaigns}) {
  console.log(campaigns)
  return (
    <div className={styles.container}>
      <Head>
        <title>Campaigns on LaunchGood</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="jumbotron ">
        <h1 className="jumbotron-heading text-center py-5">
        Campaigns on LaunchGood
        </h1>

        <div class="">
        </div>
          <div class="d-flex justify-content-center my-3">
            <div class="dropdown mx-2">
                <button class="btn btn-secondary dropdown-toggle rounded-pill" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Sort
            </button>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                    <a class="dropdown-item" href="">Zakat</a>
                </div>
            </div>
            <div class="dropdown mx-2">
                <button class="btn btn-secondary dropdown-toggle rounded-pill" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Filter
            </button>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                    <a class="dropdown-item" href="#">Action</a>
                    <a class="dropdown-item" href="#">Another action</a>
                    <a class="dropdown-item" href="#">Something else here</a>
                </div>
            </div>
        </div>
        
        <div class="album py-5">
        <div class="container">

            <div class="row">

            <CampaignCard />
                
            </div>
        </div>
    </div>

       
      </main>
    </div>
  )
}
